# global context
[build]
  publish = "dist"
  command = "gulp build"
# build a preview (optional)
[context.deploy-preview]
  command = "gulp build_preview"

[[redirects]]
from = "/secret/*"
force = true
status = 200
conditions = {Role=["member","admin","client"]}

[[redirects]]
from = "/secret/*"
to = "/secret/denied/index.html"
force = true
status = 200
